project_name: TL1A-PET-Imaging-Agent-for-IBD-1.455
data_dir: data
scripts_dir: scripts
results_dir: results
prodrug_results: results/prodrug
formulation_results: results/formulation
biobetter_results: results/biobetter
biotransformer_jar: scripts/BioTransformer3.0.jar
fab_pdb: data/fab_model.pdb
fc_pdb: data/Fc_FcRn_complex.pdb
log_level: INFO
constants:
  eff: 0.45
  k_accessible_weight_cdr: 0.5