name: tl1a-pet-imaging
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - rdkit>=2024.3
  - biopython>=1.84
  - prody>=2.4
  - pandas>=2.2
  - numpy>=1.26
  - scikit-learn>=1.4
  - matplotlib>=3.8
  - seaborn>=0.13
  - requests>=2.31
  - pip
  - pip:
    - requests-toolbelt>=1.0
