#!/usr/bin/env python3
# scripts/inputs.py

# Central file for all molecules and sequences in the TL1A PET Imaging Agent program

# Note: Validation should be performed within each experiment script where inputs
# are actually consumed, not at import time.

# Small Molecules
NOTA_CHELATOR_SMILES = "OC(=O)CN1CCN(CCN(CC(=O)O)CC(=O)O)CC1"
LINKER_CHELATOR_SMILES = "C1CN(CC(N(CCN1CC(=O)O)CC(=O)O)CC2=CC=C(C=C2)N=C=S)CC(=O)O"

# Fab Sequences
fab_sequences = {
    "Fab06_VH": "EVQLVESGGGLVQPGGSLRLSCAASGFTSGYSMHINWVRQAPGKGLEWVAVISYDGGDANYNPNLKDKATLTVDTSSSTAYMQLSSLTSEDSAVYYCARGLYGSDWYFDYFDYWGQGTLVTVSS",
    "Fab06_VL": "DIVMTQSPSSLSASVGDRVTITCRASQSNYGTSYWYQQKPGKAPKLLIYDASRATGVPDRFSGSGSGTDFTLTISSLQPEDFATYYCQQYNNYPTFGGGTKLEIK",
    "Fab11_VH": "EVQLVESGGGLVQPGGSLRLSCAASGFTSGYSMHINWVRQAPGKGLEWVAVISYDGGDANYNPNLKDKATLTVDTSSSTAYMQLSSLTSEDSAVYYCARGYSSGDWYFDYFDYWGQGTLVTVSS",
    "Fab11_VL": "DIVMTQSPSSLSASVGDRVTITCRASQSNYGTSYWYQQKPGKAPKLLIYDASRATGVPDRFSGSGSGTDFTLTISSLQPEDFATYYCQQYNNWPTFGGGTKLEIK",
}

# Biobetter Sequences
FC_SEQUENCE = "DKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
FCRN_ALPHA_CHAIN_SEQUENCE = "AESHLSLLYHLTAVSSPAPGTPAFWCSVLHEGLHNEKVSLRTLELGKHNFSLEAQIYKEFQGKDIFLPSGCGDSRGLLTQTVSGLQAEGDDISPDPLGTSFEALGNLIVVTHEFYPPLKNVSFRNQQPALSLQGFFPDNGRLYLQGRTWGWLAWLQQGWDSGQIANKIDDNTYSERLGLAKDWDSGTFMCIFLHSGLSFYNLSM"
FCRN_BETA2M_SEQUENCE = "MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM"