# scripts/inputs.py

# Central file for all molecules and sequences in the TL1A PET Imaging Agent program

import scripts.error_handling as eh

# Validate inputs on import
try:
    eh.validate_smiles(NOTA_CHELATOR_SMILES, "NOTA_Chelator")
    eh.validate_smiles(LINKER_CHELATOR_SMILES, "Linker_Chelator")

    for name, seq in fab_sequences.items():
        eh.validate_sequence(seq, f"Fab_{name}")

    eh.validate_sequence(FC_SEQUENCE, "FC_Sequence")
    eh.validate_sequence(FCRN_ALPHA_CHAIN_SEQUENCE, "FcRn_Alpha")
    eh.validate_sequence(FCRN_BETA2M_SEQUENCE, "FcRn_Beta2M")

except eh.ValidationError as e:
    print(f"Input validation failed: {e}")
    raise

# Small Molecules
NOTA_CHELATOR_SMILES = "OC(=O)CN1CCN(CCN(CC(=O)O)CC(=O)O)CC1"
LINKER_CHELATOR_SMILES = "C1CN(CC(N(CCN1CC(=O)O)CC(=O)O)CC2=CC=C(C=C2)N=C=S)CC(=O)O"

# Fab Sequences
fab_sequences = {
    "Fab06_VH": "EVQLVESGGGLVQPGGSLRLSCAASGFTSGYSMHINWVRQAPGKGLEWVAVISYDGGDANYNPNLKDKATLTVDTSSSTAYMQLSSLTSEDSAVYYCARGLYGSDWYFDYFDYWGQGTLVTVSS",
    "Fab06_VL": "DIVMTQSPSSLSASVGDRVTITCRASQSNYGTSYWYQQKPGKAPKLLIYDASRATGVPDRFSGSGSGTDFTLTISSLQPEDFATYYCQQYNNYPTFGGGTKLEIK",
    "Fab11_VH": "EVQLVESGGGLVQPGGSLRLSCAASGFTSGYSMHINWVRQAPGKGLEWVAVISYDGGDANYNPNLKDKATLTVDTSSSTAYMQLSSLTSEDSAVYYCARGYSSGDWYFDYFDYWGQGTLVTVSS",
    "Fab11_VL": "DIVMTQSPSSLSASVGDRVTITCRASQSNYGTSYWYQQKPGKAPKLLIYDASRATGVPDRFSGSGSGTDFTLTISSLQPEDFATYYCQQYNNWPTFGGGTKLEIK",
}

# Biobetter Sequences
FC_SEQUENCE = "DKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
FCRN_ALPHA_CHAIN_SEQUENCE = "AESHLSLLYHLTAVSSPAPGTPAFWCSVLHEGLHNEKVSLRTLELGKHNFSLEAQIYKEFQGKDIFLPSGCGDSRGLLTQTVSGLQAEGDDISPDPLGTSFEALGNLIVVTHEFYPPLKNVSFRNQQPALSLQGFFPDNGRLYLQGRTWGWLAWLQQGWDSGQIANKIDDNTYSERLGLAKDWDSGTFMCIFLHSGLSFYNLSM"
FCRN_BETA2M_SEQUENCE = "MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM"